ver 1.0
geo-tat/warehouse pull request #1
Opened 2024-04-18 14:34 UTC by geo-tat

2024-04-21 18:51 UTC, GUR-ok commented
Давай назовем мр "Task1: add price increase scheduling" а не "ver 1.0". именно с таким комментарием в итоге смержится сквошнутый коммит в девелоп

2024-04-21 19:03 UTC, GUR-ok requested changes

2024-04-21 19:03 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/scheduling/SimpleProductPriceScheduler.java
> +    private BigDecimal percentage;
форматирование чет поехало. тут не ругается и прям так инжектит сразу в BigDecimal?

2024-04-21 19:03 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/scheduling/SimpleProductPriceScheduler.java
> +        final Collection<Product> products = repository.findAll();
зачем Collection, почему не List?

2024-04-21 19:03 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/scheduling/SimpleProductPriceScheduler.java
> +        System.out.println("START SIMPLE SCHEDULER!");
sout меняем на логирование

2024-04-21 19:03 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/scheduling/SimpleProductPriceScheduler.java
> +        BigDecimal increaseAmount = oldPrice.multiply(percentage.divide(new BigDecimal(100)));
Ну т.е. у нас в конфиге 10.1. мы делим 10.1 на 100, получаем 0.101. и цену умножаем на 0.101. верно?

2024-04-21 19:03 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/scheduling/SimpleProductPriceScheduler.java
> +
лишние пустые строки

2024-04-21 19:03 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/service/ProductServiceImpl.java
> +        UUID id = UUID.randomUUID();
1. это не относится к задаче
2. генерить uuid как раз должен хибернейт, а не мы

2024-04-21 19:03 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/util/DatabaseSeeder.java
> +public class DatabaseSeeder {
этот класс убрать

2024-04-22 04:17 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +             PreparedStatement statement = connection.prepareStatement("UPDATE products SET price = price + (price * ?)")) {
вопрос про cpu снят

2024-04-22 04:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +    private void save(Connection connection) throws SQLException, IOException {
Метод давай назовем по-другому. непонятно что за save. а по факту это запись в файл

2024-04-22 04:21 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +        } catch (SQLException e) {
Может в один общий catch объедим и отловим все Exception

2024-04-22 09:00 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/annotation/MethodTimeMeasurementAspect.java
> +        Object result = joinPoint.proceed();
Исправил

2024-04-22 09:27 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/annotation/MethodTimeMeasurementAspect.java
> +        System.out.println(joinPoint.getSignature() + " executed in " + durationSeconds + " seconds");
Исправил

2024-04-22 09:36 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +             PreparedStatement statement = connection.prepareStatement("UPDATE products SET price = price + (price * ?)")) {
Не поддается форматированию

2024-04-22 10:02 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +                    writer.write(productId + "," + sku + "," + productName + "," + description + "," + category + "," + productPrice + "," + quantity + "," + created + "," + updatedQuantity + "\n");
Выполнил

2024-04-22 10:07 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +            try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM products")) {
Если я вас правильно понял, то исправил

2024-04-22 10:11 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/scheduling/SimpleProductPriceScheduler.java
> +    private BigDecimal percentage;
Исправил. Нет, все проходит

2024-04-22 10:18 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/scheduling/SimpleProductPriceScheduler.java
> +        final Collection<Product> products = repository.findAll();
Привычка такая,  если нет каких-либо особых требований к функционалу, то использую Collection, да и трансформировать можно, при надобности

2024-04-22 10:22 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/scheduling/SimpleProductPriceScheduler.java
> +        System.out.println("START SIMPLE SCHEDULER!");
Исправил

2024-04-22 10:32 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/scheduling/SimpleProductPriceScheduler.java
> +        BigDecimal increaseAmount = oldPrice.multiply(percentage.divide(new BigDecimal(100)));
Да
![image](https://github.com/geo-tat/warehouse/assets/116814591/1181b8da-8972-4366-b37c-8df1cd85ff9a)

2024-04-22 10:35 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/service/ProductServiceImpl.java
> +        UUID id = UUID.randomUUID();
Да, я помню этот момент в лекции, планирую внести изменения в ветке с техдолгом

2024-04-22 10:38 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/util/DatabaseSeeder.java
> +public class DatabaseSeeder {
Я в чате вопрос задавал на этот счет, сказали оставить. 
Убрал.

2024-04-22 10:49 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +    private void save(Connection connection) throws SQLException, IOException {
Исправил на saveToFile

2024-04-22 10:56 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +        } catch (SQLException e) {
Исправил

2024-04-25 13:31 UTC, GUR-ok commented
кинь мне инвайт на котрибьютера плз, а то я не могу резолвить замечания

2024-04-25 13:31 UTC, GUR-ok commented
нужно поправить конфликты

2024-04-25 13:32 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/scheduling/SimpleProductPriceScheduler.java
> +    private BigDecimal percentage;
ок

2024-04-25 13:35 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +             PreparedStatement statement = connection.prepareStatement("SELECT * FROM products");
пусть будет так. но я имел ввиду, что конекшн в ресурсах трая уже есть. поэтому statement и resultset можно вообще не клозить и не выносить в ресурсы, а просто использовать как локальные переменные. они заклозятся итак, когда закроется конекшн. Давай оставим как сейчас, это тоже ок

2024-04-29 12:56 UTC, geo-tat commented
Могу мержить?

2024-05-01 11:13 UTC, GUR-ok approved these changes

2024-05-01 11:13 UTC, GUR-ok commented
можно мержить со сквошем

2024-05-01 11:50 UTC, merged