Task4: add order and customer functionality
geo-tat/warehouse pull request #12
Opened 2024-05-09 19:52 UTC by geo-tat

Мне очень не нравится тонна беспорядочного кода, что я написал, в выходные буду сидеть оптимизировать

![image](https://github.com/geo-tat/warehouse/assets/116814591/0e5166bc-b838-41d7-9147-520f96261047)

2024-05-12 09:20 UTC, GUR-ok requested changes

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/model/Order.java
> +
здесь нужно будет добавить добавить связь oneToMany с заказанными товарами, о причинах будет в сервисе

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/model/OrderedProduct.java
> +import lombok.*;
импорты

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/model/OrderedProduct.java
> +    private int quantity;
Оберткой давай, чтобы ноль не проставился взамен null

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/model/OrderedProductId.java
> +import lombok.*;
импорты

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        return orderToSave.getId();
скинь плз скрин запросов хибернейта

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        List<Product> productsForOrder = getProductsForOrderFromWarehouse(dto.getProducts());
а что если мы нашли не все товары? В запросе пришлот10, а нашли 9. Ты еще ищешь по isAvailable.. они в список не включаются. а как же исключение?

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        Customer customer = customerRepository.findById(customerId)
кастомер же извлекается вместе с заказом? зачем его отдельно дергать?

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        List<OrderedProduct> oldOrderedProducts = orderedProductRepository.findAllByOrderId(orderId);
у тебя здесь селектится ордер а потом селектится oldOrderedProducts.
Причем на 107 строке orderedProduct.getProduct().getId() приведет к еще одной серии селектов.
Если в order добавить связь oneToMany с заказанными товарами, то весь ордер со всеми потрохами на 3 уровня вложенности можно будет получить одним запросом
```
    @Query("""
                select o from OrderEntity o
                left join fetch o.orderedProducts ps
                left join fetch ps.product p
                where o.id = :orderId
           """)
    Optional<OrderEntity> findByIdFetchOrderedProducts(UUID orderId);
```

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +
здесь тоже хотелось бы увидеть скрин запросов хибернейта

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        List<OrderedProduct> orderedProducts = orderedProductRepository.findAllByOrderId(orderId);
здесь аналогично. тк нет свзяи order - orderedProduct в хибернейте, мы тут слеектим все по отдельности. даже кастомера.

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        return "";
"" не пойдет. void

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        return "";
"" не пойдет. void

2024-05-12 09:20 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +}
Алгоритмы для справки:
Создание заказа
1. Проверили кастомера, что он есть, если нет исключение
2. Находим все товары из запроса по айди одним селектом через findByIdIn, делаем из этого хэшмапу productId -> productEntity
3. Создаем предварительно orderEntity, чтобы его сеттить в orderedProduct
4. По данным товаров из запроса проходимся стримом и собираем OrderedProduct, используя хэшмапу из шага два. Тут же проверяем количество и isAvailable
5. Сеттим в ордер эти товары. и сохраняемся 1 раз, сохраняя только ордер, остальное каскадно

Апдейт товаров в заказе
1. Получаем ордер со всеми потрохами одним запросом. Проверяем статус и кастомера.
2. Находим все товары из запроса по айди одним селектом через findByIdIn, делаем из этого хэшмапу productId -> productEntity
3. По данным товаров из запроса проходимся стримом и собираем новый OrderedProduct или апдейтим старый, используя хэшмапу из шага два. Потребуется определять, есть ли товар уже в заказе, возможно сделать еще одну мапу. Тут же проверяем количество и isAvailable
4. Сохраняем ордер каскадно сохраняется все остальное

2024-05-17 10:14 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        return orderToSave.getId();
Hibernate: 
    insert 
    into
        orders
        (customer_id, delivery_address, status, id) 
    values
        (?, ?, ?, ?)
Hibernate: 
    insert 
    into
        ordered_product
        (price, quantity, status, order_id, product_id) 
    values
        (?, ?, ?, ?, ?)
Hibernate: 
    insert 
    into
        ordered_product
        (price, quantity, status, order_id, product_id) 
    values
        (?, ?, ?, ?, ?)
Hibernate: 
    update
        product 
    set
        category=?,
        created=?,
        description=?,
        is_available=?,
        name=?,
        price=?,
        quantity=?,
        sku=?,
        updated_quantity=? 
    where
        id=?
Hibernate: 
    update
        product 
    set
        category=?,
        created=?,
        description=?,
        is_available=?,
        name=?,
        price=?,
        quantity=?,
        sku=?,
        updated_quantity=? 
    where
        id=?

2024-05-17 10:50 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        return orderToSave.getId();
![image](https://github.com/geo-tat/warehouse/assets/116814591/cd3f8741-b681-4d76-868e-7358620a7335)

2024-05-17 10:58 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +
![image](https://github.com/geo-tat/warehouse/assets/116814591/11dd31a3-8fec-4bc4-bc9c-1bb9381f6599)

2024-05-17 12:31 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        List<Product> productsForOrder = getProductsForOrderFromWarehouse(dto.getProducts());
Исправил. Я почему то думал, что заказ в любом случае должен оформляться (Из тех товаров, что остались)

2024-05-17 12:35 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        Customer customer = customerRepository.findById(customerId)
Исправил

2024-05-17 16:35 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        List<OrderedProduct> oldOrderedProducts = orderedProductRepository.findAllByOrderId(orderId);
Изменил

2024-05-17 17:07 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        Customer customer = customerRepository.findById(customerId)
Исправил

2024-05-17 17:07 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        Customer customer = customerRepository.findById(customerId)
Исправил

2024-05-23 04:43 UTC, GUR-ok approved these changes
Ок, давай подмержим со сквошем

2024-05-23 07:37 UTC, merged