Feature/task5
geo-tat/warehouse pull request #13
Opened 2024-05-23 14:14 UTC by geo-tat

Добавлен эндпоинт GET: /order/info

2024-06-01 11:30 UTC, GUR-ok commented
название мр поправить!

2024-06-01 11:36 UTC, GUR-ok requested changes
Нет асинхронности, тк ждем вызов сначала одного сервиса, потом второго

2024-06-01 11:36 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/config/WebClientConfig.java
> +    @Bean(name = "accountWebClient")
можно просто оставить bean без опций внутри скобок. спринг будет смотреть на название метода и название проперти куда инжектить, чтобы определить квалифаер

2024-06-01 11:36 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/crm/CrmProvider.java
> +public class CrmProvider {
класс не нужен, тк не дает никакой логики. клиентов достаточно

2024-06-01 11:36 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/crm/CrmServiceClientImpl.java
> +                .delayElement(Duration.ofSeconds(3))
делэй делается не тут. а в логике внешнего сервиса

2024-06-01 11:36 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/crm/CrmServiceClientImpl.java
> +                .delayElement(Duration.ofSeconds(3))
сделай еще тогда мок имплементацию CrmServiceClient. там юзай supplyAsync И там жди 3 сек.

2024-06-01 11:36 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        Map<String, String> uins = getUins(logins);
Ты получается делаешь вызов первого сервиса и вызываешь на CompletableFuture метод join() (в приватном методе getAccount). Второй сервис даже не вызвался. Мы будем ждать 3 сек, пока первый отработает. Потом вызовем второй и опять ждать 3 сек. Разве это правильно? Мы хотим вызвать два сервиса одновременно сначала просто, не запрашивая результат здесь и сейчас. Каждый будет по 3 сек параллельно формировать результат. Т.е. тебе нужно объявить две переменные CompletableFuture, в них записать вызов сервисов. join вызывать внутри главного большого стрима

итог: поправить и самое главное проверить! Если каждый сервис отвечает по 3 сек, у тебя на метод должно затратить чуть более 3 сек. а не 3+3.

2024-06-03 15:37 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/config/WebClientConfig.java
> +    @Bean(name = "accountWebClient")
Поправил

2024-06-03 18:46 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/crm/CrmProvider.java
> +public class CrmProvider {
Убрал

2024-06-08 08:29 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/order/service/OrderServiceImpl.java
> +        Map<String, String> uins = getUins(logins);
![image](https://github.com/geo-tat/warehouse/assets/116814591/0c5b6c21-d31a-4a14-b1c2-bed2755903f6)
Исправил

2024-06-08 09:09 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/crm/CrmServiceClientImpl.java
> +                .delayElement(Duration.ofSeconds(3))
Перенес дилей во внешние сервисы.
Сделал моки.

2024-06-08 09:30 UTC, GUR-ok approved these changes
Хорошо, давай подмержим)

2024-06-08 12:12 UTC, merged