Task7: add upload/download images function, add exception-handler-starter
geo-tat/warehouse pull request #19
Opened 2024-06-13 07:47 UTC by geo-tat

add exception-handler-starter

2024-06-15 10:48 UTC, GUR-ok requested changes

2024-06-15 10:48 UTC, GUR-ok commented on src/main/resources/db/changelog/v3/create-image-table.xml
> +        <createTable tableName="image">
Добавь условие плз
 ```
  <preConditions onFail="MARK_RAN">
        <not>
            <tableExists tableName="image"/>
        </not>
  </preConditions>
```

2024-06-15 10:48 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/product/storage/S3Storage.java
> +    public String uploadFile(File convertedFile) throws IOException {
возвращать uuid

2024-06-15 10:48 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/product/storage/S3Storage.java
> +        S3Object s3Object = s3Client.getObject(bucketName, fileKey);
давай везде final сделаем, где объявляем локальные переменные. Например final S3Object s3Object. Во всех методах этого класса и классе ImageServiceImpl

2024-06-15 10:48 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/product/controller/ProductController.java
> +    String uploadImage(@PathVariable UUID id,
возвращаем uuid айдишник файла

2024-06-15 10:48 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/product/controller/ProductController.java
> +    byte[] downloadImage(@PathVariable UUID id) throws IOException {
мы должны тут архив скачивать. нейминг метода поменять, что-нибудь про zip

2024-06-15 10:48 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/product/controller/ProductController.java
> +
Давай byte[] заменим на StreamingResponseBody. Так лучше по памяти по использованию тредов.

Псевдокодный пример как передать outputStream в сервис
```
    @GetMapping("/foo")
    public ResponseEntity<StreamingResponseBody> downloadZip() {
        StreamingResponseBody stream = outputStream-> {
            вызовСервисаДляЗагрузкиАрхива(outputStream);
        };
        
        return ResponseEntity.ok()
            .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=archivename.zip")
            .contentType(MediaType.APPLICATION_OCTET_STREAM)
            .body(stream );
    }
```

В сервисном методе outputStream принимается в аргументах. и потом ZipoutputStream создается через конструктор с этим outputStream. В сервисе будет ```ZipOutputStream zipOutputStream = new ZipOutputStream(outputStream)```. При этом сервисный метод может ничего не возвращать.

2024-06-15 10:48 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/product/service/ImageServiceImpl.java
> +    public byte[] download(UUID id) throws IOException {
тут в аргументах будет приниматься outputStream, и именно с ним будет создаваться ZipOutputStream zipOutputStream = new ZipOutputStream(outputStream).
Сам метод может стать void

2024-06-15 10:48 UTC, GUR-ok commented on src/main/resources/db/changelog/v3/create-image-table.xml
> +            <column name="s3_file_id" type="VARCHAR(255)">
давай объединим s3_file_id и id. не нужно две колонки разных под одно смысловое поле

2024-06-26 12:20 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/product/service/ImageServiceImpl.java
> +    public byte[] download(UUID id) throws IOException {
Исправил

2024-06-26 13:15 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/product/controller/ProductController.java
> +    byte[] downloadImage(@PathVariable UUID id) throws IOException {
Исправил

2024-06-26 13:15 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/product/controller/ProductController.java
> +    String uploadImage(@PathVariable UUID id,
Исправил

2024-06-26 13:16 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/product/storage/S3Storage.java
> +    public String uploadFile(File convertedFile) throws IOException {
Исправил

2024-06-26 13:46 UTC, geo-tat commented on src/main/resources/db/changelog/v3/create-image-table.xml
> +            <column name="s3_file_id" type="VARCHAR(255)">
Исправил

2024-06-26 16:23 UTC, merged