Task2: add multi-criteria searching
geo-tat/warehouse pull request #6
Opened 2024-04-25 19:47 UTC by geo-tat

2024-04-27 12:19 UTC, GUR-ok requested changes

2024-04-27 12:19 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/controller/ProductController.java
> +    public Collection<ProductDtoOut> multiCriteriaSearch(@RequestBody List<SearchCriteria<?>> criteriaList,
грубая ошибка - в GET запросе нельзя передавать реквест боди

2024-04-27 12:19 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/controller/ProductController.java
> +                                                         @RequestParam(name = "from", defaultValue = "0") int from,
давай не разбивать на 3 параметра а сразу принимать Pageable

2024-04-27 12:19 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/repository/ProductRepository.java
>      Optional<Product> findById(UUID id);
нужно репозиторий экстендить от ```JpaSpecificationExecutor<Product>```, тогда ```Page<Product> findAll(Specification<Product> specification, Pageable pageable);``` будет доступен из коробки, его не нужно объявлять отдлеьно

2024-04-27 12:19 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/search/criteria/BigDecimalSearchCriteria.java
> +    public String getField() {
зачем вручную геттеры если из дает @data

2024-04-27 12:19 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/search/criteria/BigDecimalSearchCriteria.java
> +    public PredicateStrategy<BigDecimal> getStrategy() {
этот геттер останется, тк поле статик

2024-04-27 12:19 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/search/enums/OperationType.java
> +            case "=", "EQUAL" -> EQUAL;
символы и названия енумов уже есть в енумах.
можно так
```
package com.crudshop.demo.service.search.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum OperationType {

    EQUAL("="),
    GRATER_THAN_OR_EQ(">="),
    LESS_THAN_OR_EQ("<="),
    LIKE("~");

    private final String code;

    OperationType(String code) {
        this.code = code;
    }

    @JsonValue
    public String getCode() {
        return code;
    }

    @JsonCreator
    public static OperationType fromCode(String code) {
        for (OperationType operationType : OperationType.values()) {
            if (operationType.name().equals(code) || operationType.code.equals(code)) {
                return operationType;
            }
        } return null;
    }
}
```
или вообще так
```
import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonProperty;

public enum OperationType {
    @JsonProperty("operation")
    @JsonAlias({"="})
    EQUAL,

    @JsonProperty("operation")
    @JsonAlias({">="})
    GRATER_THAN_OR_EQ,

    @JsonProperty("operation")
    @JsonAlias({"<="})
    LESS_THAN_OR_EQ,

    @JsonProperty("operation")
    @JsonAlias({"~"})
    LIKE;
}
```

2024-04-27 12:19 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/service/ProductService.java
> +    Collection<ProductDtoOut> multiCriteriaSearch(List<SearchCriteria<?>> criteriaList, int from, int size, String sort);
тут будут не отдельные параметры а сразу pageable

2024-04-27 12:19 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/service/ProductServiceImpl.java
> +        return (root, query, cb) -> {
давай логику формирования спецификации в отдельный класс
```
@RequiredArgsConstructor
public class ProductSpecification implements Specification<Product> {

    private final List<SearchCriteria> criteriaList;

    @Override
    public Predicate toPredicate(
            @NonNull Root<ProductEntity> root,
            @NonNull CriteriaQuery<?> query,
            @NonNull CriteriaBuilder cb
    ) {
...
```
тогда ```Specification<Product> specification = buildSpecification(criteriaList);``` заменится на что-то типа
```
        final ProductSpecification spec = new ProductSpecification(criteriaList);
```

2024-04-27 12:19 UTC, GUR-ok commented on src/main/java/ru/mediasoft/warehouse/util/SortingMapper.java
> +public class SortingMapper {
если сразу принимать pageable, это не нужно

2024-04-27 12:19 UTC, GUR-ok commented on src/test/java/ru/mediasoft/warehouse/service/ProductServiceImplTest.java
> +import java.util.*;
импорты разворачиваем

2024-04-27 12:19 UTC, GUR-ok commented on src/test/java/ru/mediasoft/warehouse/service/ProductServiceIntegrationalTest.java
> +    ProductService service;
может не делать testconfig а тут создать ProductService через вызов конструктора?

2024-04-29 09:07 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/controller/ProductController.java
> +                                                         @RequestParam(name = "from", defaultValue = "0") int from,
Исправил.

2024-04-29 09:28 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/search/criteria/BigDecimalSearchCriteria.java
> +    public String getField() {
Исправил

2024-04-29 09:44 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/search/enums/OperationType.java
> +            case "=", "EQUAL" -> EQUAL;
Спасибо, исправил

2024-04-29 09:44 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/util/SortingMapper.java
> +public class SortingMapper {
Класс удалил

2024-04-29 09:59 UTC, geo-tat commented on src/test/java/ru/mediasoft/warehouse/service/ProductServiceIntegrationalTest.java
> +    ProductService service;
Мне здесь нечем аргументировать, я забыл, что можно так вот просто через конструктор создать service и все ломал голову, как c dataJpaTest работать, потом вот наткнулся, что можно создавать бины таким образом. А какой вариант оптимальнее в данном случае, сказать не могу. Зато теперь знаю больше (=

2024-04-29 12:52 UTC, geo-tat commented on src/main/java/ru/mediasoft/warehouse/service/ProductServiceImpl.java
> +        return (root, query, cb) -> {
Переделал

2024-05-01 11:14 UTC, GUR-ok approved these changes
можно мержить со сквошем

2024-05-01 11:57 UTC, merged